config/routes.rb
Rails.application.routes.draw do

  root 'registrations#new'

  resources :cats, only: [:index, :show, :edit, :update]

  get  "/register", to: "registrations#new"
  post "/register", to: "registrations#create"

  post   "/login",  to: "login#create"
  delete "/logout", to: "login#destroy"

  namespace :api do
    namespace :v1 do
      resources :cats, only: [:index, :show]
    end
  end
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  # http://api.rubyonrails.org/classes/ActiveModel/SecurePassword/ClassMethods.html
  # http://stackoverflow.com/questions/10139954/does-has-secure-password-use-any-form-of-salting
  has_secure_password

  validates :name, :email, presence: true, length: { in: 2..255 }

  scope :visible, -> { where(visible: true) }
  scope :hidden,  -> { where(visble: false) }

  # More info
  # http://guides.rubyonrails.org/association_basics.html
  # https://www.railstutorial.org/book/frontmatter
  # http://apidock.com/rails/ActiveRecord/Associations/ClassMethods/has_many
  # http://stackoverflow.com/questions/5856838/scope-with-join-on-has-many-through-association
  has_many :follower_relations
  has_many :followed_relations, class_name: "FollowerRelation", foreign_key: "followed_cat_id"

  has_many :followers,    -> { visible }, through: :follower_relations, source: :followed
  has_many :followed_by,  -> { visible }, through: :followed_relations, source: :cat
end

app/controllers/api/v1/cats_controller.rb
module Api
  module V1
    class CatsController < ApplicationController
      # http://www.ruby-doc.org/core-2.1.3/Array.html
      # http://en.wikibooks.org/wiki/Ruby_Programming/Syntax/Variables_and_Constants#Constants
      DEFAULT_FIELDS = %w{ name birthday followers_count followed_by_count links }

      # http://leopard.in.ua/2012/07/08/using-cors-with-rails/
      after_action :set_access_control_headers

      def index
        offset = params[:offset] || 0
        limit  = params[:limit]  || 10

        order  = params[:order] || "id ASC"

        # Maybe the user wants to specify the set of fields is interested with in order to do a fastest request
        fields = params[:fields].try(:split, ",") || DEFAULT_FIELDS

        cats   = Cat.visible.order(order).limit(limit).offset(offset)

        result = cats.map do |cat|
          # http://www.ruby-doc.org/core-2.1.3/Array.html#method-i-map
          # http://ruby-doc.org/core-2.1.3/Object.html#method-i-tap
          # http://stackoverflow.com/questions/17493080/advantage-of-tap-method-in-ruby
          {}.tap do |cat_hash|
            cat_hash[:name]              = cat.name                     if fields.include?("name") && cat.name
            cat_hash[:birthday]          = cat.birthday                 if fields.include?("birthday") && cat.email
            cat_hash[:followers_count]   = cat.follower_relations.count if fields.include?("followers_count")
            cat_hash[:followed_by_count] = cat.followed_relations.count if fields.include?("followed_by_count")

            if fields.include?("links")
              cat_hash[:links] = {
                public: cat_url(cat),
                api: api_v1_cat_url(cat)
              }
            end
          end
        end

        render json: result
      end

      # DO IT YOURSELF!
      # A LOT of repeated code in this controller. How can we extract it?
      def show
        fields = params[:fields].try(:split, ",") || DEFAULT_FIELDS

        cat    = Cat.visible.find(params[:id])

        result = {}.tap do |cat_hash|
          cat_hash[:name]              = cat.name                     if fields.include?("name") && cat.name
          cat_hash[:birthday]          = cat.birthday                 if fields.include?("birthday") && cat.email
          cat_hash[:followers_count]   = cat.follower_relations.count if fields.include?("followers_count")
          cat_hash[:followed_by_count] = cat.followed_relations.count if fields.include?("followed_by_count")
          if fields.include?("links")
            cat_hash[:links] = {
              public: cat_url(cat),
              api: api_v1_cat_url(cat)
            }
          end
        end

        render json: result
      rescue ActiveRecord::RecordNotFound
        # http://apidock.com/rails/ActionController/Base/render#254-List-of-status-codes-and-their-symbols
        head :not_found
      end

      def set_access_control_headers
        headers['Access-Control-Allow-Origin'] = "*"
        headers['Access-Control-Request-Method'] = "GET"
      end

    end
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  # http://api.rubyonrails.org/classes/ActiveSupport/Rescuable/ClassMethods.html
  rescue_from Pundit::NotAuthorizedError, with: :deny_access

  include Pundit

  before_action :load_cat_of_the_month, only: :index
  before_action :load_cat, except: :index

  def index
    page  = params[:page].to_i || 1

    # page scope is provided by kamikari gem
    # https://github.com/amatsuda/kaminari/blob/master/lib/kaminari/models/active_record_model_extension.rb#L13
    @cats = policy_scope(Cat).order("id ASC").page(page)
  end

  def show
    authorize @cat
  end

  def edit
    authorize @cat
  end

  def update
    authorize @cat

    if @cat.update(cats_params)
      # http://guides.rubyonrails.org/action_controller_overview.html#the-flash
      flash[:notice] = "Cat updated successfully"

      redirect_to cat_path(@cat)
    else
      flash[:error]  = "Ops! We couldn't update the cat, please review the errors"

      render :edit
    end
  end

  private

  def load_cat
    @cat = Cat.find(params[:id])
  end

  def cats_params
    params.require(:cat).permit(:name, :birthday, :visible)
  end

  # Do you think this is a good place to put this logic?
  # Where would you move it?
  def load_cat_of_the_month
    last_month_follower_relation = FollowerRelation.where("EXTRACT(MONTH FROM created_at) = ? AND EXTRACT(YEAR FROM created_at) = ?", 1.month.ago.month, 1.month.ago.year)

    current_time       = Time.now
    date_of_expiration = current_time.end_of_month - current_time

    # You could also use Rails.cache.read and Rails.cache.write! Review the documentation :)

    @cat_of_the_month = Rails.cache.fetch("cat_of_the_month", expires_in: date_of_expiration) do
      # First alternative
      # Retrieve results from database without order and use ruby function to order hash
      count_of_followers = last_month_follower_relation.group(:followed_cat_id).count
      # http://www.rubyinside.com/how-to/ruby-sort-hash
      cat_of_the_month_data = count_of_followers.sort_by { |k, v| -v }.first

      Cat.find(cat_of_the_month_data.first) if cat_of_the_month_data
    end

    # # Second alternative
    # # Order the results with SQL query an retrieve one result
    # # I just googled "Order by group by count" to find this solution
    # cat_of_month_id = last_month_follower_relation.
    #   group(:followed_cat_id).
    #   select("followed_cat_id, COUNT(*) as followers_count").
    #   order("followers_count DESC").
    #   limit(1).first.try(:followed_cat_id)
    #
    # # http://apidock.com/rails/Object/try
    #
    # @cat_of_the_month = Cat.find(cat_of_month_id) if cat_of_month_id
  end

  def deny_access
    # http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html
    # http://apidock.com/rails/ActionController/Base/render#254-List-of-status-codes-and-their-symbols
    render text: "Your are not authorized to perform this action", status: :unauthorized
  end
end

app/helpers/cats_helper.rb
module CatsHelper
  def localize_date(date)
    I18n.l date, format: :short if date
  end
end

app/views/cats/_login_form.html.erb
<%# http://api.rubyonrails.org/classes/ActionView/Helpers/FormTagHelper.html %>
<%= form_tag login_path do %>
  <%= label_tag :email %>
  <%= text_field_tag :email, nil, placeholder: "email" %>
  <%= label_tag :password %>
  <%= password_field_tag :password, nil, placeholder: "password" %>

  <%= submit_tag "Login" %>
<% end %>
<%= link_to "Register", register_path %>

app/views/cats/_logout_form.html.erb
<%= form_tag logout_path, method: :delete do %>
  <%= submit_tag "Logout" %>
<% end %>

app/views/cats/edit.html.erb
<h1>Edit :: <%= @cat.name %></h1>

<% if @cat.errors.any? %>
  <ul>
    <% @cat.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @cat do |c| %>
  <div class="form-group">
    <%= c.label :name, "Cat name" %>
    <%= c.text_field :name, placeholder: "Ej. Marramiau", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= c.label :birthday, "Birthday" %>
    <%= c.date_field :birthday, class: "form-control" %>
  </div>
  <div class="checkbox">
    <%= c.label :visible do %>
      <%= c.check_box :visible %> Visible
    <% end %>
  </div>

  <%= c.submit "Edit cat info!", class: "btn btn-default" %>
<% end %>

app/views/cats/index.html.erb
<h1>Listing cats</h1>

<% if current_cat %>
  <h2><%= t(:welcome, name: current_cat.name) %></h2>
  <p>
    AJAX
    <br>
    <%# http://edgeguides.rubyonrails.org/working_with_javascript_in_rails.html %>
    <%= link_to "Logout", logout_path, method: :delete, confirm: 'Logout?', remote: true %>
  </p>
  <p>
    Non AJAX
    <br>
    <%= render "logout_form" %>
    </p>
<% else %>
  <%# http://guides.rubyonrails.org/layouts_and_rendering.html#using-partials %>
  <%= render "login_form" %>
<% end %>

<% if @cat_of_the_month %>
  <h2>Cat with more followers last month</h2>
  <p>
    <%= link_to @cat_of_the_month.name, cat_path(@cat_of_the_month) %>
  </p>
<% end %>

<div id="api-data-response">
  <%= link_to "Perfom api request", "#", id: "api-data-perform-link" %>
</div>

<script>
  $("#api-data-perform-link").click(function() {
    $.ajax({
      url: '<%= api_v1_cats_path %>',
      data: { offset: 1, limit: 1 },
      dataType: "json"
    }).done(function(response) {
      $("#api-data-response").html(JSON.stringify(response));
    });
  });
</script>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Birthday</th>
      <th>Followers count</th>
      <th>Followed by count</th>
      <th>Options</th>
    </tr>
  </thead>
  <tbody>
    <% @cats.each do |cat| %>
      <% if policy(cat).show? %>
          <tr>
            <% cache(cat) do %>
              <td><%= link_to cat.name, cat_path(cat) %></td>
              <td><%= localize_date cat.birthday %></td>
              <td><%= cat.followers.count %></td>
              <td><%= cat.followed_by.count %></td>
            <% end %>
            <td>
              <% if policy(cat).edit? %>
                <%= link_to "Edit", edit_cat_path(cat) %>
              <% end %>
            </td>
          </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= paginate @cats %>

app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<h2>Info</h2>

<dl class="dl-horizontal">
  <dt>Birthday</dt>
  <dd><%= localize_date @cat.birthday %></dd>
</dl>

<%# Don't you see here some repetion? %>

<h2>Following</h2>

<ul>
  <% @cat.followers.each do |follower| %>
    <li><strong><%= follower.name %></strong></li>
  <% end %>
</ul>

<h2>Followers</h2>

<ul>
  <% @cat.followed_by.each do |follower| %>
    <li><strong><%= follower.name %></strong></li>
  <% end %>
</ul>

<%= link_to "Back", cats_path %>